name: sign-in  

on:  
  schedule:  
    - cron: '08 0 * * 1-5'   # 每个工作日 8:08（UTC）  
    - cron: '08 2 * * 1-5'    # 每个工作日 10:08（UTC）  
    - cron: '58 7 * * 2'      # 每周二 15:58（UTC）  
    - cron: '58 9 * * 2'      # 每周二 17:58（UTC）  
    - cron: '08 2 * * 1'      # 每周一 10:08（UTC）  
    - cron: '08 2 * * 3'      # 每周三 10:08（UTC）  
    - cron: '08 0 * * 4'      # 每周四 8:08（UTC）  
    - cron: '08 2 * * 4'      # 每周四 10:08（UTC）  
    - cron: '08 0 * * 5'      # 每周五 8:08（UTC）  
    - cron: '08 2 * * 5'      # 每周五 10:08（UTC）  
  workflow_dispatch:  # 允许手动触发工作流  

jobs:  
  run_script:  
    runs-on: ubuntu-latest  
    timeout-minutes: 10  # 设置超时时间为 10 分钟  
    env:  
      TZ: Asia/Shanghai  # 设置时区为亚洲/上海，确保脚本运行在北京时间  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
      
      - name: Set up Python  
        uses: actions/setup-python@v2  
        with:  
          python-version: '3.9'  
      
      - name: Install dependencies  
        run: |  
          pip install -r requirements.txt  
      
      - name: Run signment_02.py  
        run: |  
          python ./signment_02.py  
          
      - name: Run Tests  
        run: |  
          python test_sign_in.py  # 运行你的测试文件
